apiVersion: v1
kind: Service
metadata:
  name: lab
  namespace: kubectl config view | grep namespace
spec:
  selector:
    app: lab
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080